import { MobImageData } from "./MobImageData";

export class MobImagesDefinition {
	static mobImages: MobImageData[] = [
		new MobImageData("Item", "Dropped Item", 0),
		new MobImageData("XPOrb", "Experience Orb", 1),
		new MobImageData("AreaEffectCloud", "Area Effect Cloud", 2),
		new MobImageData("ThrownEgg", "Egg", 3),
		new MobImageData("LeashKnot", "Lead Knot", 4),
		new MobImageData("Painting", "Painting", 5),
		new MobImageData("Arrow", "Arrow", 6),
		new MobImageData("Snowball", "Snowball", 7),
		new MobImageData("Fireball", "Ghast Fireball", 8),
		new MobImageData("SmallFireball", "Blaze Fireball", 9),
		new MobImageData("ThrownEnderpearl", "Ender Pearl", 10),
		new MobImageData("EyeOfEnderSignal", "Eye of Ender", 11),
		new MobImageData("ThrownPotion", "Splash Potion", 12),
		new MobImageData("ThrownExpBottle", "Bottle o' Enchanting", 13),
		new MobImageData("ItemFrame", "Item Frame", 14),
		new MobImageData("WitherSkull", "Wither Skull", 15),
		new MobImageData("PrimedTnt", "Primed TNT", 16),
		new MobImageData("FallingSand", "Falling Block", 17),
		new MobImageData("FireworksRocketEntity", "Firework Rocket", 18),
		new MobImageData("SpectralArrow", "Spectral Arrow", 19),
		new MobImageData("ShulkerBullet", "Shulker Bullet", 20),
		new MobImageData("DragonFireball", "Dragon Fireball", 21),
		new MobImageData("ArmorStand", "Armor Stand", 22),
		new MobImageData("MinecartCommandBlock", "Minecart with Command Block", 23),
		new MobImageData("Boat", "Boat", 24),
		new MobImageData("MinecartRideable", "Minecart", 25),
		new MobImageData("MinecartChest", "Storage Minecart", 26),
		new MobImageData("MinecartFurnace", "Powered Minecart", 27),
		new MobImageData("MinecartTNT", "Minecart with TNT", 28),
		new MobImageData("MinecartHopper", "Minecart with Hopper", 29),
		new MobImageData("MinecartSpawner", "Minecart with Spawner", 30),
		new MobImageData("Creeper", "Creeper", 31),
		new MobImageData("Skeleton", "Skeleton", 32),
		new MobImageData("Spider", "Spider", 33),
		new MobImageData("Giant", "Giant Zombie", 34),
		new MobImageData("Zombie", "Zombie", 35),
		new MobImageData("Slime", "Slime", 36),
		new MobImageData("Ghast", "Ghast", 37),
		new MobImageData("PigZombie", "Zombie Pigman", 38),
		new MobImageData("Enderman", "Enderman", 39),
		new MobImageData("CaveSpider", "Cave Spider", 40),
		new MobImageData("Silverfish", "Silverfish", 41),
		new MobImageData("Blaze", "Blaze", 42),
		new MobImageData("LavaSlime", "Magma Cube", 43),
		new MobImageData("MagmaCube", "Magma Cube", 43),
		new MobImageData("EnderDragon", "Ender Dragon", 44),
		new MobImageData("WitherBoss", "Wither", 45),
		new MobImageData("Bat", "Bat", 46),
		new MobImageData("Witch", "Witch", 47),
		new MobImageData("Endermite", "Endermite", 48),
		new MobImageData("Guardian", "Guardian", 49),
		new MobImageData("Shulker", "Shulker", 50),
		new MobImageData("Pig", "Pig", 51),
		new MobImageData("Sheep", "Sheep", 52),
		new MobImageData("Cow", "Cow", 53),
		new MobImageData("Chicken", "Chicken", 54),
		new MobImageData("Squid", "Squid", 55),
		new MobImageData("Wolf", "Wolf", 56),
		new MobImageData("MushroomCow", "Mooshroom", 57),
		new MobImageData("SnowMan", "Snow Golem", 58),
		new MobImageData("Ozelot", "Ocelot", 59),
		new MobImageData("VillagerGolem", "Iron Golem", 60),
		new MobImageData("EntityHorse", "Horse", 61),
		new MobImageData("Donkey", "Donkey", 62),
		new MobImageData("Mule", "Mule", 63),
		new MobImageData("ZombieHorse", "Zombie Horse", 64),
		new MobImageData("SkeletonHorse", "Skeleton Horse", 65),
		new MobImageData("Rabbit", "Rabbit", 66),
		new MobImageData("PolarBear", "Polar Bear", 67),
		new MobImageData("Llama", "Llama", 68),
		new MobImageData("Parrot", "Parrot", 69),
		new MobImageData("Villager", "Villager", 70),
		new MobImageData("Vindicator", "Vindicator", 71),
		new MobImageData("Evoker", "Evoker", 72),
		new MobImageData("Vex", "Vex", 73),
		new MobImageData("Stray", "Stray", 74),
		new MobImageData("Illusioner", "Illusioner", 75),
		new MobImageData("EnderCrystal", "Ender Crystal", 76),
		new MobImageData("ZombieVillager", "Zombie Villager", 77),
		new MobImageData("ElderGuardian", "Elder Gaurdian", 78),
		new MobImageData("Husk", "Husk", 79),
		new MobImageData("WitherSkeleton", "Wither Skeleton", 80)
	];

	static professionImages: MobImageData[] = [
		new MobImageData("Farmer", "Farmer", 0),
		new MobImageData("Librarian", "Librarian", 1),
		new MobImageData("Priest", "Priest", 2),
		new MobImageData("Blacksmith", "Blacksmith", 3),
		new MobImageData("Butcher", "Butcher", 4),
		new MobImageData("Nitwit", "Nitwit", 5)
	];
}